version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: image-qa-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: image_qa_rewards
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app-network

  app:
    build: .
    container_name: image-qa-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/image_qa_rewards?authSource=admin
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-secret-key-here
      - GOOGLE_CLIENT_ID=your-google-client-id
      - GOOGLE_CLIENT_SECRET=your-google-client-secret
      - WEBHOOK_SECRET=your-webhook-secret
      - PII_ENC_KEY=your-32-byte-hex-key-here
      - N8N_WORKFLOW_URL=https://your-n8n-workflow-url
      - N8N_API_KEY=your-n8n-api-key
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
